# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Stateman: Resan mot social kompetens"
email: stateman@wunderkinder.io
description: >
  Field rapporterna från en vanlig man som försöker lära sig game. Självklart skriven på välfärdsspråket!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://state-man.github.io" # the base hostname & protocol for your site
github_username:  state-man

# Build settings
markdown: kramdown
